# Generated by Django 4.0.2 on 2022-02-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='situacao',
            field=models.CharField(choices=[('realizado', 'REALIZADO'), ('cancelado', 'CANCELADO'), ('agendado', 'AGENDADO')], default='agendado', max_length=9, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
